#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_sistema")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertPessoas(Pessoas instance);
    partial void UpdatePessoas(Pessoas instance);
    partial void DeletePessoas(Pessoas instance);
    partial void InsertVenda(Venda instance);
    partial void UpdateVenda(Venda instance);
    partial void DeleteVenda(Venda instance);
    partial void InsertItensVenda(ItensVenda instance);
    partial void UpdateItensVenda(ItensVenda instance);
    partial void DeleteItensVenda(ItensVenda instance);
    partial void InsertStatusPagamento(StatusPagamento instance);
    partial void UpdateStatusPagamento(StatusPagamento instance);
    partial void DeleteStatusPagamento(StatusPagamento instance);
    partial void InsertContasReceber(ContasReceber instance);
    partial void UpdateContasReceber(ContasReceber instance);
    partial void DeleteContasReceber(ContasReceber instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertItensAluguel(ItensAluguel instance);
    partial void UpdateItensAluguel(ItensAluguel instance);
    partial void DeleteItensAluguel(ItensAluguel instance);
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    partial void InsertAlugar(Alugar instance);
    partial void UpdateAlugar(Alugar instance);
    partial void DeleteAlugar(Alugar instance);
    partial void InsertVestuario(Vestuario instance);
    partial void UpdateVestuario(Vestuario instance);
    partial void DeleteVestuario(Vestuario instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::sistema.DAL.Properties.Settings.Default.db_sistemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Pessoas> Pessoas
		{
			get
			{
				return this.GetTable<Pessoas>();
			}
		}
		
		public System.Data.Linq.Table<Venda> Venda
		{
			get
			{
				return this.GetTable<Venda>();
			}
		}
		
		public System.Data.Linq.Table<ItensVenda> ItensVenda
		{
			get
			{
				return this.GetTable<ItensVenda>();
			}
		}
		
		public System.Data.Linq.Table<StatusPagamento> StatusPagamento
		{
			get
			{
				return this.GetTable<StatusPagamento>();
			}
		}
		
		public System.Data.Linq.Table<ContasReceber> ContasReceber
		{
			get
			{
				return this.GetTable<ContasReceber>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<ItensAluguel> ItensAluguel
		{
			get
			{
				return this.GetTable<ItensAluguel>();
			}
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionario
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
		
		public System.Data.Linq.Table<Alugar> Alugar
		{
			get
			{
				return this.GetTable<Alugar>();
			}
		}
		
		public System.Data.Linq.Table<Vestuario> Vestuario
		{
			get
			{
				return this.GetTable<Vestuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descricao;
		
		private EntitySet<Vestuario> _Vestuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public Categoria()
		{
			this._Vestuario = new EntitySet<Vestuario>(new Action<Vestuario>(this.attach_Vestuario), new Action<Vestuario>(this.detach_Vestuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desc_categoria", Storage="_Descricao", DbType="NVarChar(20)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_tb_vestuario", Storage="_Vestuario", ThisKey="Codigo", OtherKey="CodigoCategoria")]
		public EntitySet<Vestuario> Vestuario
		{
			get
			{
				return this._Vestuario;
			}
			set
			{
				this._Vestuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vestuario(Vestuario entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Vestuario(Vestuario entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa")]
	public partial class Pessoas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoPessoa;
		
		private string _Nome;
		
		private string _Telefone;
		
		private string _Email;
		
		private EntitySet<Venda> _Venda;
		
		private EntityRef<Usuarios> _Usuarios;
		
		private EntitySet<Alugar> _Alugar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoPessoaChanging(int value);
    partial void OnCodigoPessoaChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Pessoas()
		{
			this._Venda = new EntitySet<Venda>(new Action<Venda>(this.attach_Venda), new Action<Venda>(this.detach_Venda));
			this._Usuarios = default(EntityRef<Usuarios>);
			this._Alugar = new EntitySet<Alugar>(new Action<Alugar>(this.attach_Alugar), new Action<Alugar>(this.detach_Alugar));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_CodigoPessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoPessoa
		{
			get
			{
				return this._CodigoPessoa;
			}
			set
			{
				if ((this._CodigoPessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._CodigoPessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome", Storage="_Nome", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="telefone", Storage="_Telefone", DbType="VarChar(30)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="email", Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Venda", Storage="_Venda", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa")]
		public EntitySet<Venda> Venda
		{
			get
			{
				return this._Venda;
			}
			set
			{
				this._Venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Usuarios", Storage="_Usuarios", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsUnique=true, IsForeignKey=false)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Pessoas = null;
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Pessoas = this;
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Alugar", Storage="_Alugar", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa")]
		public EntitySet<Alugar> Alugar
		{
			get
			{
				return this._Alugar;
			}
			set
			{
				this._Alugar.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Pessoas = this;
		}
		
		private void detach_Venda(Venda entity)
		{
			this.SendPropertyChanging();
			entity.Pessoas = null;
		}
		
		private void attach_Alugar(Alugar entity)
		{
			this.SendPropertyChanging();
			entity.Pessoas = this;
		}
		
		private void detach_Alugar(Alugar entity)
		{
			this.SendPropertyChanging();
			entity.Pessoas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoVenda;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<decimal> _Desconto;
		
		private System.Nullable<decimal> _ValorPago;
		
		private System.Nullable<int> _CodigoPessoa;
		
		private EntitySet<ItensVenda> _ItensVenda;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
		private EntityRef<Pessoas> _Pessoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnDescontoChanging(System.Nullable<decimal> value);
    partial void OnDescontoChanged();
    partial void OnValorPagoChanging(System.Nullable<decimal> value);
    partial void OnValorPagoChanged();
    partial void OnCodigoPessoaChanging(System.Nullable<int> value);
    partial void OnCodigoPessoaChanged();
    #endregion
		
		public Venda()
		{
			this._ItensVenda = new EntitySet<ItensVenda>(new Action<ItensVenda>(this.attach_ItensVenda), new Action<ItensVenda>(this.detach_ItensVenda));
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			this._Pessoas = default(EntityRef<Pessoas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_CodigoVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desconto", Storage="_Desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Desconto
		{
			get
			{
				return this._Desconto;
			}
			set
			{
				if ((this._Desconto != value))
				{
					this.OnDescontoChanging(value);
					this.SendPropertyChanging();
					this._Desconto = value;
					this.SendPropertyChanged("Desconto");
					this.OnDescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor_pago", Storage="_ValorPago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ValorPago
		{
			get
			{
				return this._ValorPago;
			}
			set
			{
				if ((this._ValorPago != value))
				{
					this.OnValorPagoChanging(value);
					this.SendPropertyChanging();
					this._ValorPago = value;
					this.SendPropertyChanged("ValorPago");
					this.OnValorPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_CodigoPessoa", DbType="Int")]
		public System.Nullable<int> CodigoPessoa
		{
			get
			{
				return this._CodigoPessoa;
			}
			set
			{
				if ((this._CodigoPessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._CodigoPessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ItensVenda", Storage="_ItensVenda", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ItensVenda> ItensVenda
		{
			get
			{
				return this._ItensVenda;
			}
			set
			{
				this._ItensVenda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ContasReceber", Storage="_ContasReceber", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Venda", Storage="_Pessoas", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoas Pessoas
		{
			get
			{
				return this._Pessoas.Entity;
			}
			set
			{
				Pessoas previousValue = this._Pessoas.Entity;
				if (((previousValue != value) 
							|| (this._Pessoas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pessoas.Entity = null;
						previousValue.Venda.Remove(this);
					}
					this._Pessoas.Entity = value;
					if ((value != null))
					{
						value.Venda.Add(this);
						this._CodigoPessoa = value.CodigoPessoa;
					}
					else
					{
						this._CodigoPessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Pessoas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensVenda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_ItensVenda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class ItensVenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Quantidade;
		
		private int _CodigoVestuario;
		
		private int _CodigoVenda;
		
		private decimal _Valor;
		
		private int _CodigoItem;
		
		private EntityRef<Venda> _Venda;
		
		private EntityRef<Vestuario> _Vestuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuantidadeChanging(int value);
    partial void OnQuantidadeChanged();
    partial void OnCodigoVestuarioChanging(int value);
    partial void OnCodigoVestuarioChanged();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnCodigoItemChanging(int value);
    partial void OnCodigoItemChanged();
    #endregion
		
		public ItensVenda()
		{
			this._Venda = default(EntityRef<Venda>);
			this._Vestuario = default(EntityRef<Vestuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="quantidade", Storage="_Quantidade", DbType="Int NOT NULL")]
		public int Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_vestuario", Storage="_CodigoVestuario", DbType="Int NOT NULL")]
		public int CodigoVestuario
		{
			get
			{
				return this._CodigoVestuario;
			}
			set
			{
				if ((this._CodigoVestuario != value))
				{
					this.OnCodigoVestuarioChanging(value);
					this.SendPropertyChanging();
					this._CodigoVestuario = value;
					this.SendPropertyChanged("CodigoVestuario");
					this.OnCodigoVestuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_CodigoVenda", DbType="Int NOT NULL")]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_item", Storage="_CodigoItem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoItem
		{
			get
			{
				return this._CodigoItem;
			}
			set
			{
				if ((this._CodigoItem != value))
				{
					this.OnCodigoItemChanging(value);
					this.SendPropertyChanging();
					this._CodigoItem = value;
					this.SendPropertyChanged("CodigoItem");
					this.OnCodigoItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ItensVenda", Storage="_Venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.ItensVenda.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.ItensVenda.Add(this);
						this._CodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._CodigoVenda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_vestuario_ItensVenda", Storage="_Vestuario", ThisKey="CodigoVestuario", OtherKey="CodigoVestuario", IsForeignKey=true)]
		public Vestuario Vestuario
		{
			get
			{
				return this._Vestuario.Entity;
			}
			set
			{
				Vestuario previousValue = this._Vestuario.Entity;
				if (((previousValue != value) 
							|| (this._Vestuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vestuario.Entity = null;
						previousValue.ItensVenda.Remove(this);
					}
					this._Vestuario.Entity = value;
					if ((value != null))
					{
						value.ItensVenda.Add(this);
						this._CodigoVestuario = value.CodigoVestuario;
					}
					else
					{
						this._CodigoVestuario = default(int);
					}
					this.SendPropertyChanged("Vestuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status_pagamento")]
	public partial class StatusPagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoStatus;
		
		private string _Status;
		
		private EntitySet<ContasReceber> _ContasReceber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoStatusChanging(int value);
    partial void OnCodigoStatusChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public StatusPagamento()
		{
			this._ContasReceber = new EntitySet<ContasReceber>(new Action<ContasReceber>(this.attach_ContasReceber), new Action<ContasReceber>(this.detach_ContasReceber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_CodigoStatus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoStatus
		{
			get
			{
				return this._CodigoStatus;
			}
			set
			{
				if ((this._CodigoStatus != value))
				{
					this.OnCodigoStatusChanging(value);
					this.SendPropertyChanging();
					this._CodigoStatus = value;
					this.SendPropertyChanged("CodigoStatus");
					this.OnCodigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPagamento_ContasReceber", Storage="_ContasReceber", ThisKey="CodigoStatus", OtherKey="CodigoStatus")]
		public EntitySet<ContasReceber> ContasReceber
		{
			get
			{
				return this._ContasReceber;
			}
			set
			{
				this._ContasReceber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = this;
		}
		
		private void detach_ContasReceber(ContasReceber entity)
		{
			this.SendPropertyChanging();
			entity.StatusPagamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class ContasReceber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoConta;
		
		private System.DateTime _DataCompra;
		
		private System.DateTime _DataVencimento;
		
		private System.Nullable<System.DateTime> _DataPagamento;
		
		private int _CodigoVenda;
		
		private int _CodigoStatus;
		
		private EntityRef<StatusPagamento> _StatusPagamento;
		
		private EntityRef<Venda> _Venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoContaChanging(int value);
    partial void OnCodigoContaChanged();
    partial void OnDataCompraChanging(System.DateTime value);
    partial void OnDataCompraChanged();
    partial void OnDataVencimentoChanging(System.DateTime value);
    partial void OnDataVencimentoChanged();
    partial void OnDataPagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPagamentoChanged();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnCodigoStatusChanging(int value);
    partial void OnCodigoStatusChanged();
    #endregion
		
		public ContasReceber()
		{
			this._StatusPagamento = default(EntityRef<StatusPagamento>);
			this._Venda = default(EntityRef<Venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_conta", Storage="_CodigoConta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoConta
		{
			get
			{
				return this._CodigoConta;
			}
			set
			{
				if ((this._CodigoConta != value))
				{
					this.OnCodigoContaChanging(value);
					this.SendPropertyChanging();
					this._CodigoConta = value;
					this.SendPropertyChanged("CodigoConta");
					this.OnCodigoContaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_compra", Storage="_DataCompra", DbType="Date NOT NULL")]
		public System.DateTime DataCompra
		{
			get
			{
				return this._DataCompra;
			}
			set
			{
				if ((this._DataCompra != value))
				{
					this.OnDataCompraChanging(value);
					this.SendPropertyChanging();
					this._DataCompra = value;
					this.SendPropertyChanged("DataCompra");
					this.OnDataCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_vencimento", Storage="_DataVencimento", DbType="Date NOT NULL")]
		public System.DateTime DataVencimento
		{
			get
			{
				return this._DataVencimento;
			}
			set
			{
				if ((this._DataVencimento != value))
				{
					this.OnDataVencimentoChanging(value);
					this.SendPropertyChanging();
					this._DataVencimento = value;
					this.SendPropertyChanged("DataVencimento");
					this.OnDataVencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_pagamento", Storage="_DataPagamento", DbType="Date")]
		public System.Nullable<System.DateTime> DataPagamento
		{
			get
			{
				return this._DataPagamento;
			}
			set
			{
				if ((this._DataPagamento != value))
				{
					this.OnDataPagamentoChanging(value);
					this.SendPropertyChanging();
					this._DataPagamento = value;
					this.SendPropertyChanged("DataPagamento");
					this.OnDataPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_CodigoVenda", DbType="Int NOT NULL")]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_CodigoStatus", DbType="Int NOT NULL")]
		public int CodigoStatus
		{
			get
			{
				return this._CodigoStatus;
			}
			set
			{
				if ((this._CodigoStatus != value))
				{
					this.OnCodigoStatusChanging(value);
					this.SendPropertyChanging();
					this._CodigoStatus = value;
					this.SendPropertyChanged("CodigoStatus");
					this.OnCodigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StatusPagamento_ContasReceber", Storage="_StatusPagamento", ThisKey="CodigoStatus", OtherKey="CodigoStatus", IsForeignKey=true)]
		public StatusPagamento StatusPagamento
		{
			get
			{
				return this._StatusPagamento.Entity;
			}
			set
			{
				StatusPagamento previousValue = this._StatusPagamento.Entity;
				if (((previousValue != value) 
							|| (this._StatusPagamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StatusPagamento.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._StatusPagamento.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._CodigoStatus = value.CodigoStatus;
					}
					else
					{
						this._CodigoStatus = default(int);
					}
					this.SendPropertyChanged("StatusPagamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venda_ContasReceber", Storage="_Venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.ContasReceber.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.ContasReceber.Add(this);
						this._CodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._CodigoVenda = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Usuario;
		
		private string _Senha;
		
		private int _CodigoPessoa;
		
		private EntityRef<Pessoas> _Pessoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnCodigoPessoaChanging(int value);
    partial void OnCodigoPessoaChanged();
    #endregion
		
		public Usuarios()
		{
			this._Pessoas = default(EntityRef<Pessoas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="senha", Storage="_Senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_CodigoPessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodigoPessoa
		{
			get
			{
				return this._CodigoPessoa;
			}
			set
			{
				if ((this._CodigoPessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._CodigoPessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Usuarios", Storage="_Pessoas", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoas Pessoas
		{
			get
			{
				return this._Pessoas.Entity;
			}
			set
			{
				Pessoas previousValue = this._Pessoas.Entity;
				if (((previousValue != value) 
							|| (this._Pessoas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pessoas.Entity = null;
						previousValue.Usuarios = null;
					}
					this._Pessoas.Entity = value;
					if ((value != null))
					{
						value.Usuarios = this;
						this._CodigoPessoa = value.CodigoPessoa;
					}
					else
					{
						this._CodigoPessoa = default(int);
					}
					this.SendPropertyChanged("Pessoas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_alugar")]
	public partial class ItensAluguel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoItem;
		
		private System.Nullable<int> _Quantidade;
		
		private System.Nullable<int> _CodigoVestuario;
		
		private System.Nullable<int> _CodigoAluguel;
		
		private System.Nullable<decimal> _Valor;
		
		private EntityRef<Alugar> _Alugar;
		
		private EntityRef<Vestuario> _Vestuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoItemChanging(int value);
    partial void OnCodigoItemChanged();
    partial void OnQuantidadeChanging(System.Nullable<int> value);
    partial void OnQuantidadeChanged();
    partial void OnCodigoVestuarioChanging(System.Nullable<int> value);
    partial void OnCodigoVestuarioChanged();
    partial void OnCodigoAluguelChanging(System.Nullable<int> value);
    partial void OnCodigoAluguelChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    #endregion
		
		public ItensAluguel()
		{
			this._Alugar = default(EntityRef<Alugar>);
			this._Vestuario = default(EntityRef<Vestuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_item", Storage="_CodigoItem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoItem
		{
			get
			{
				return this._CodigoItem;
			}
			set
			{
				if ((this._CodigoItem != value))
				{
					this.OnCodigoItemChanging(value);
					this.SendPropertyChanging();
					this._CodigoItem = value;
					this.SendPropertyChanged("CodigoItem");
					this.OnCodigoItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="quantidade", Storage="_Quantidade", DbType="Int")]
		public System.Nullable<int> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_vestuario", Storage="_CodigoVestuario", DbType="Int")]
		public System.Nullable<int> CodigoVestuario
		{
			get
			{
				return this._CodigoVestuario;
			}
			set
			{
				if ((this._CodigoVestuario != value))
				{
					this.OnCodigoVestuarioChanging(value);
					this.SendPropertyChanging();
					this._CodigoVestuario = value;
					this.SendPropertyChanged("CodigoVestuario");
					this.OnCodigoVestuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_aluguel", Storage="_CodigoAluguel", DbType="Int")]
		public System.Nullable<int> CodigoAluguel
		{
			get
			{
				return this._CodigoAluguel;
			}
			set
			{
				if ((this._CodigoAluguel != value))
				{
					this.OnCodigoAluguelChanging(value);
					this.SendPropertyChanging();
					this._CodigoAluguel = value;
					this.SendPropertyChanged("CodigoAluguel");
					this.OnCodigoAluguelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alugar_ItensAluguel", Storage="_Alugar", ThisKey="CodigoAluguel", OtherKey="CodigoAlugar", IsForeignKey=true)]
		public Alugar Alugar
		{
			get
			{
				return this._Alugar.Entity;
			}
			set
			{
				Alugar previousValue = this._Alugar.Entity;
				if (((previousValue != value) 
							|| (this._Alugar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alugar.Entity = null;
						previousValue.ItensAluguel.Remove(this);
					}
					this._Alugar.Entity = value;
					if ((value != null))
					{
						value.ItensAluguel.Add(this);
						this._CodigoAluguel = value.CodigoAlugar;
					}
					else
					{
						this._CodigoAluguel = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alugar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_vestuario_ItensAluguel", Storage="_Vestuario", ThisKey="CodigoVestuario", OtherKey="CodigoVestuario", IsForeignKey=true)]
		public Vestuario Vestuario
		{
			get
			{
				return this._Vestuario.Entity;
			}
			set
			{
				Vestuario previousValue = this._Vestuario.Entity;
				if (((previousValue != value) 
							|| (this._Vestuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vestuario.Entity = null;
						previousValue.ItensAluguel.Remove(this);
					}
					this._Vestuario.Entity = value;
					if ((value != null))
					{
						value.ItensAluguel.Add(this);
						this._CodigoVestuario = value.CodigoVestuario;
					}
					else
					{
						this._CodigoVestuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vestuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_funcionarios")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoFuncionario;
		
		private string _Nome;
		
		private string _Cargo;
		
		private string _Telefone;
		
		private EntitySet<Alugar> _Alugar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoFuncionarioChanging(int value);
    partial void OnCodigoFuncionarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    #endregion
		
		public Funcionario()
		{
			this._Alugar = new EntitySet<Alugar>(new Action<Alugar>(this.attach_Alugar), new Action<Alugar>(this.detach_Alugar));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_funcionario", Storage="_CodigoFuncionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoFuncionario
		{
			get
			{
				return this._CodigoFuncionario;
			}
			set
			{
				if ((this._CodigoFuncionario != value))
				{
					this.OnCodigoFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._CodigoFuncionario = value;
					this.SendPropertyChanged("CodigoFuncionario");
					this.OnCodigoFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome", Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cargo", Storage="_Cargo", DbType="VarChar(50)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="telefone", Storage="_Telefone", DbType="VarChar(50)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcionario_Alugar", Storage="_Alugar", ThisKey="CodigoFuncionario", OtherKey="CodigoFuncionario")]
		public EntitySet<Alugar> Alugar
		{
			get
			{
				return this._Alugar;
			}
			set
			{
				this._Alugar.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alugar(Alugar entity)
		{
			this.SendPropertyChanging();
			entity.Funcionario = this;
		}
		
		private void detach_Alugar(Alugar entity)
		{
			this.SendPropertyChanging();
			entity.Funcionario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_aluguel")]
	public partial class Alugar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoAlugar;
		
		private string _Vestuario;
		
		private System.Nullable<System.DateTime> _Entrada;
		
		private System.Nullable<System.DateTime> _Saida;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<int> _CodigoPessoa;
		
		private System.Nullable<int> _CodigoFuncionario;
		
		private string _Status;
		
		private System.Nullable<decimal> _Desconto;
		
		private System.Nullable<decimal> _Sinal;
		
		private string _FormaDePagamento;
		
		private string _Cliente;
		
		private string _Telefone;
		
		private EntitySet<ItensAluguel> _ItensAluguel;
		
		private EntityRef<Pessoas> _Pessoas;
		
		private EntityRef<Funcionario> _Funcionario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoAlugarChanging(int value);
    partial void OnCodigoAlugarChanged();
    partial void OnVestuarioChanging(string value);
    partial void OnVestuarioChanged();
    partial void OnEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnEntradaChanged();
    partial void OnSaidaChanging(System.Nullable<System.DateTime> value);
    partial void OnSaidaChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnCodigoPessoaChanging(System.Nullable<int> value);
    partial void OnCodigoPessoaChanged();
    partial void OnCodigoFuncionarioChanging(System.Nullable<int> value);
    partial void OnCodigoFuncionarioChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDescontoChanging(System.Nullable<decimal> value);
    partial void OnDescontoChanged();
    partial void OnSinalChanging(System.Nullable<decimal> value);
    partial void OnSinalChanged();
    partial void OnFormaDePagamentoChanging(string value);
    partial void OnFormaDePagamentoChanged();
    partial void OnClienteChanging(string value);
    partial void OnClienteChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    #endregion
		
		public Alugar()
		{
			this._ItensAluguel = new EntitySet<ItensAluguel>(new Action<ItensAluguel>(this.attach_ItensAluguel), new Action<ItensAluguel>(this.detach_ItensAluguel));
			this._Pessoas = default(EntityRef<Pessoas>);
			this._Funcionario = default(EntityRef<Funcionario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_aluguel", Storage="_CodigoAlugar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoAlugar
		{
			get
			{
				return this._CodigoAlugar;
			}
			set
			{
				if ((this._CodigoAlugar != value))
				{
					this.OnCodigoAlugarChanging(value);
					this.SendPropertyChanging();
					this._CodigoAlugar = value;
					this.SendPropertyChanged("CodigoAlugar");
					this.OnCodigoAlugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="vestuario", Storage="_Vestuario", DbType="VarChar(50)")]
		public string Vestuario
		{
			get
			{
				return this._Vestuario;
			}
			set
			{
				if ((this._Vestuario != value))
				{
					this.OnVestuarioChanging(value);
					this.SendPropertyChanging();
					this._Vestuario = value;
					this.SendPropertyChanged("Vestuario");
					this.OnVestuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="entrada", Storage="_Entrada", DbType="Date")]
		public System.Nullable<System.DateTime> Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this.OnEntradaChanging(value);
					this.SendPropertyChanging();
					this._Entrada = value;
					this.SendPropertyChanged("Entrada");
					this.OnEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="saida", Storage="_Saida", DbType="Date")]
		public System.Nullable<System.DateTime> Saida
		{
			get
			{
				return this._Saida;
			}
			set
			{
				if ((this._Saida != value))
				{
					this.OnSaidaChanging(value);
					this.SendPropertyChanging();
					this._Saida = value;
					this.SendPropertyChanged("Saida");
					this.OnSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_CodigoPessoa", DbType="Int")]
		public System.Nullable<int> CodigoPessoa
		{
			get
			{
				return this._CodigoPessoa;
			}
			set
			{
				if ((this._CodigoPessoa != value))
				{
					this.OnCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._CodigoPessoa = value;
					this.SendPropertyChanged("CodigoPessoa");
					this.OnCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_funcionario", Storage="_CodigoFuncionario", DbType="Int")]
		public System.Nullable<int> CodigoFuncionario
		{
			get
			{
				return this._CodigoFuncionario;
			}
			set
			{
				if ((this._CodigoFuncionario != value))
				{
					this.OnCodigoFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._CodigoFuncionario = value;
					this.SendPropertyChanged("CodigoFuncionario");
					this.OnCodigoFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desconto", Storage="_Desconto", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Desconto
		{
			get
			{
				return this._Desconto;
			}
			set
			{
				if ((this._Desconto != value))
				{
					this.OnDescontoChanging(value);
					this.SendPropertyChanging();
					this._Desconto = value;
					this.SendPropertyChanged("Desconto");
					this.OnDescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sinal", Storage="_Sinal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Sinal
		{
			get
			{
				return this._Sinal;
			}
			set
			{
				if ((this._Sinal != value))
				{
					this.OnSinalChanging(value);
					this.SendPropertyChanging();
					this._Sinal = value;
					this.SendPropertyChanged("Sinal");
					this.OnSinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="forma_de_pagamento", Storage="_FormaDePagamento", DbType="VarChar(10)")]
		public string FormaDePagamento
		{
			get
			{
				return this._FormaDePagamento;
			}
			set
			{
				if ((this._FormaDePagamento != value))
				{
					this.OnFormaDePagamentoChanging(value);
					this.SendPropertyChanging();
					this._FormaDePagamento = value;
					this.SendPropertyChanged("FormaDePagamento");
					this.OnFormaDePagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cliente", Storage="_Cliente", DbType="VarChar(50)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this.OnClienteChanging(value);
					this.SendPropertyChanging();
					this._Cliente = value;
					this.SendPropertyChanged("Cliente");
					this.OnClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="telefone", Storage="_Telefone", DbType="VarChar(50)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alugar_ItensAluguel", Storage="_ItensAluguel", ThisKey="CodigoAlugar", OtherKey="CodigoAluguel")]
		public EntitySet<ItensAluguel> ItensAluguel
		{
			get
			{
				return this._ItensAluguel;
			}
			set
			{
				this._ItensAluguel.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pessoas_Alugar", Storage="_Pessoas", ThisKey="CodigoPessoa", OtherKey="CodigoPessoa", IsForeignKey=true)]
		public Pessoas Pessoas
		{
			get
			{
				return this._Pessoas.Entity;
			}
			set
			{
				Pessoas previousValue = this._Pessoas.Entity;
				if (((previousValue != value) 
							|| (this._Pessoas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pessoas.Entity = null;
						previousValue.Alugar.Remove(this);
					}
					this._Pessoas.Entity = value;
					if ((value != null))
					{
						value.Alugar.Add(this);
						this._CodigoPessoa = value.CodigoPessoa;
					}
					else
					{
						this._CodigoPessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Pessoas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcionario_Alugar", Storage="_Funcionario", ThisKey="CodigoFuncionario", OtherKey="CodigoFuncionario", IsForeignKey=true)]
		public Funcionario Funcionario
		{
			get
			{
				return this._Funcionario.Entity;
			}
			set
			{
				Funcionario previousValue = this._Funcionario.Entity;
				if (((previousValue != value) 
							|| (this._Funcionario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Funcionario.Entity = null;
						previousValue.Alugar.Remove(this);
					}
					this._Funcionario.Entity = value;
					if ((value != null))
					{
						value.Alugar.Add(this);
						this._CodigoFuncionario = value.CodigoFuncionario;
					}
					else
					{
						this._CodigoFuncionario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Funcionario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensAluguel(ItensAluguel entity)
		{
			this.SendPropertyChanging();
			entity.Alugar = this;
		}
		
		private void detach_ItensAluguel(ItensAluguel entity)
		{
			this.SendPropertyChanging();
			entity.Alugar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_vestuario")]
	public partial class Vestuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoVestuario;
		
		private string _Descricao;
		
		private System.Nullable<decimal> _Valor;
		
		private int _CodigoCategoria;
		
		private string _Disponibilidade;
		
		private EntitySet<ItensVenda> _ItensVenda;
		
		private EntitySet<ItensAluguel> _ItensAluguel;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoVestuarioChanging(int value);
    partial void OnCodigoVestuarioChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnCodigoCategoriaChanging(int value);
    partial void OnCodigoCategoriaChanged();
    partial void OnDisponibilidadeChanging(string value);
    partial void OnDisponibilidadeChanged();
    #endregion
		
		public Vestuario()
		{
			this._ItensVenda = new EntitySet<ItensVenda>(new Action<ItensVenda>(this.attach_ItensVenda), new Action<ItensVenda>(this.detach_ItensVenda));
			this._ItensAluguel = new EntitySet<ItensAluguel>(new Action<ItensAluguel>(this.attach_ItensAluguel), new Action<ItensAluguel>(this.detach_ItensAluguel));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_vestuario", Storage="_CodigoVestuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoVestuario
		{
			get
			{
				return this._CodigoVestuario;
			}
			set
			{
				if ((this._CodigoVestuario != value))
				{
					this.OnCodigoVestuarioChanging(value);
					this.SendPropertyChanging();
					this._CodigoVestuario = value;
					this.SendPropertyChanged("CodigoVestuario");
					this.OnCodigoVestuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desc_vestuario", Storage="_Descricao", DbType="NVarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_Valor", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_CodigoCategoria", DbType="Int NOT NULL")]
		public int CodigoCategoria
		{
			get
			{
				return this._CodigoCategoria;
			}
			set
			{
				if ((this._CodigoCategoria != value))
				{
					this.OnCodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCategoria = value;
					this.SendPropertyChanged("CodigoCategoria");
					this.OnCodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="disponibilidade", Storage="_Disponibilidade", DbType="VarChar(20)")]
		public string Disponibilidade
		{
			get
			{
				return this._Disponibilidade;
			}
			set
			{
				if ((this._Disponibilidade != value))
				{
					this.OnDisponibilidadeChanging(value);
					this.SendPropertyChanging();
					this._Disponibilidade = value;
					this.SendPropertyChanged("Disponibilidade");
					this.OnDisponibilidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_vestuario_ItensVenda", Storage="_ItensVenda", ThisKey="CodigoVestuario", OtherKey="CodigoVestuario")]
		public EntitySet<ItensVenda> ItensVenda
		{
			get
			{
				return this._ItensVenda;
			}
			set
			{
				this._ItensVenda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_vestuario_ItensAluguel", Storage="_ItensAluguel", ThisKey="CodigoVestuario", OtherKey="CodigoVestuario")]
		public EntitySet<ItensAluguel> ItensAluguel
		{
			get
			{
				return this._ItensAluguel;
			}
			set
			{
				this._ItensAluguel.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_tb_vestuario", Storage="_Categoria", ThisKey="CodigoCategoria", OtherKey="Codigo", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Vestuario.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Vestuario.Add(this);
						this._CodigoCategoria = value.Codigo;
					}
					else
					{
						this._CodigoCategoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensVenda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Vestuario = this;
		}
		
		private void detach_ItensVenda(ItensVenda entity)
		{
			this.SendPropertyChanging();
			entity.Vestuario = null;
		}
		
		private void attach_ItensAluguel(ItensAluguel entity)
		{
			this.SendPropertyChanging();
			entity.Vestuario = this;
		}
		
		private void detach_ItensAluguel(ItensAluguel entity)
		{
			this.SendPropertyChanging();
			entity.Vestuario = null;
		}
	}
}
#pragma warning restore 1591
